greeting: true
show_logo: true
bar_cursor: true
prompt_symbol: "◯"
submitted_prompt_symbol: "⬤"
show_diff: false
show_thinking: true
show_turn_stats: false
redraw_counter: false
show_ui_io: false
show_tools: full
show_messages: all-full
show_status: all
show_prompt_scroll_indicator: true
theme: tau-plain-dark
completions:
  "@": complete_agents
  "./": complete_path
  "../": complete_path
  "/": complete_path
  "~": complete_path
  "~/": complete_path
bind: {}